application/users/views.py
from flask import session, request, redirect, render_template, flash, jsonify
from .helpers import clearSessionExcept
from application.models import User
from .forms import RegistrationForm, LoginForm
from flask import Blueprint

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    """Register user"""
    # Clear session from previous login
    clearSessionExcept("csrf_token", "_flashes")

    form = RegistrationForm()
    if request.method == "POST":
        # use Flask-WTF's validation:
        if form.validate_on_submit():
            # Insert user and hashed password into database
            try:
                User.create(form.username.data, form.password.data)
                flash(f"account created for {form.username.data}!", "success")
                return redirect("/login")
            except Exception:
                flash(u"Something went wrong.", "danger")
    return render_template("register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    """Log user in"""
    # Clear session from previous login
    clearSessionExcept("_flashes", "csrf_token")

    form = LoginForm()

    if request.method == "POST":
        # use Flask-WTF's validation:
        if form.validate_on_submit():
            return redirect("/")
        else:
            return render_template("login.html", form=form), 403

    # User GET to get here
    return render_template("login.html", form=form)


@users.route("/ajax", methods=["POST"])
# Route just for trying out AJAX - checks if user exists for quick front end feedback
def ajax():
    username = request.form["username"]
    exists = False

    if User.get(username):
        exists = True
    else:
        exists = False

    return jsonify({"exists": exists})


@users.route("/logout")
def logout():
    """Log user out"""

    # Forget any user_id
    session.clear()

    # Redirect user to login form
    return redirect("/")

application/templates/apology.html
{% extends "layout.html" %}

{% block title %}
    Apology
{% endblock %}

{% block main %}
    <img alt="{{ top }}" class="border" src="http://memegen.link/custom/{{ top | urlencode }}/{{ bottom | urlencode }}.jpg?alt=https://i.imgur.com/CsCgN7Ll.png" title="{{ top }}">
{% endblock %}

application/templates/buy.html
{% extends "layout.html" %} {% block title %} Buy {% endblock %} {% block main
%}

<div>
    <span>Buy a stock from the <a href="https://www.advfn.com/nasdaq/nasdaq.asp" target="_blank">NASDAQ index</a>. Like
        TSLA, NFLX, GOOG, DDD, STX, CCC, SBUX, FOSL... To mention a few. </span><br><br>
    <form action="" method="post" onsubmit="return validateBuy(this);">
        {{ form.hidden_tag() }}
        <! –– search bar ––>
            <div class="input-group">
                {% if form.search.errors %}
                {{ form.search(class="form-control is-invalid", autocomplete="off", autofocus=true) }}
                <div class="input-group-append">
                    <! -- search button -->
                        {{ form.search_button(id="search_button", class="mybtn btn btn-outline-secondary fa-text", style="border-radius: 0.25rem;", value="&#xf002;"|safe) }}
                </div>
                <div class="invalid-feedback" style="text-align: left;">
                    {% for error in form.search.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.search(class="form-control", autocomplete="off", autofocus=true) }}
                <div class="input-group-append">
                    <! -- search button -->
                        {{ form.search_button(class="mybtn btn btn-outline-secondary fa-text", autocomplete="off", value="&#xf002;"|safe, style="border-radius: 0.25rem;") }}
                </div>
                {% endif %}
            </div>
            <! -- end of searchbar -->
                <div id="searchfeedback" class="feedback" style="text-align: left; color: #dc3545; font-size: 80%;">
                    <span></span>
                </div>

                <! -- product containter, only shows if there's a valid stock in flask session -->
                    {% if ("buystock" not in session) %}
                    <!-- User still hasn't posted anything. -->
                    <script>
                        var price = null;
                    </script>
                    {% elif "symbol" in session["buystock"] %}
                    <!-- User has searched for a valid stock. -->
                    {% set buyDict = session["buystock"] %}
                    <script>
                        var price = '{{ buyDict.price }}';
                    </script>

                    <!-- buyDict is the dictionary with stock information. -->
                    <div class="container-fluid product-container">
                        <!-- PRODUCT -->
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-12 col-sm-6" style="padding-right: 0; padding-left: 0;">
                                    <h4 class="product-name">
                                        <strong>{{ buyDict["name"] }}</strong>
                                    </h4>
                                    <h4>
                                        <small>{{ buyDict["symbol"] }}</small>
                                    </h4>
                                </div>
                                <div class="col-12 col-sm-6 text-right" style="
              margin-top: auto;
              padding-right: 0;
              padding-left: 0;
              padding-top: 10px;
            ">
                                    <div style="
                display: flex;
                justify-content: flex-end;
                align-items: center;
              ">
                                        <!--Price to the left of input field-->
                                        <span>
                                            <strong id="pricePrUnit">{{"$%.2f"|format(buyDict["price"]) }}
                                                <span class="text-muted" style="padding-right: 4px;">x</span></strong>
                                        </span>
                                        {% if form.shares.errors %}
                                        <div class="input-group float-right" style="max-width: 100px;">
                                            {{ form.shares(class="form-control is-invalid", autocomplete="off", autofocus=true, value=session['buystock']['amount'], size="4", type="number") }}
                                            <div class="input-group-append">
                                                <!-- refresh button -->
                                                {{ form.shares_button(class="mybtn btn btn-outline-secondary fa-text", value="&#xf2f1;"|safe, style="border-radius: 0.25rem;") }}
                                            </div>
                                        </div>
                                        {% else %}
                                        <!--Number input field for refresh button-->
                                        <div class="input-group float-right" style="max-width: 100px;">
                                            {{ form.shares(class="form-control", autocomplete="off", autofocus=true, value=session['buystock']['amount'], size="4", type="number") }}
                                            <div class="input-group-append">
                                                <!-- refresh button -->
                                                {{ form.shares_button(class="mybtn btn btn-outline-secondary fa-text", value="&#xf2f1;"|safe, style="border-radius: 0.25rem;") }}
                                            </div>
                                        </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            {% if form.shares.errors %}
                            <div class="feedback"
                                style="text-align: right; margin-right: -12px; color: #dc3545; font-size: 80%;">

                                <span>{{ form.shares.errors[0] }}</span>

                            </div>
                            {% endif %}
                        </div>
                        <div id="sharesfeedback" class="feedback"
                            style="text-align: right; color: #dc3545; font-size: 80%;">
                            <span></span>
                        </div>
                        <hr />
                        <!-- END PRODUCT -->
                    </div>
                    <div class="card-footer">
                        <div class="pull-right" style="margin: 10px;">
                            <! -- buy button -->
                                {{ form.buy_button(class="mybtn btn btn-primary") }}
                                <div class="pull-right" style="margin: 5px;">
                                    Total price:
                                    <b>
                                        {% if "total" in buyDict %} {{
            "$%.2f"|format(buyDict["total"]) }} {% endif %}
                                    </b>
                                </div>
                        </div>
                    </div>

                    {% endif %}
    </form>
</div>


<script>

    /*
    This script is for validation of form inputs. The validation will run on the server in any case,
    but if JS is enabled in the client's browser it will save the user some round trips to the server and the database.
    In this particular file jQuery is used a lot, but similar scripts are written in other parts of the app in pure JS.
    */

    var clickedSearch = false;
    var clickedShares = false;
    var clickedBuy = false;
    var serverAmount = '{{ 0 if buyDict is not defined else buyDict["amount"] }}';


    // Keep track of what button was clicked so validateBuy can validate correctly
    $("#search_button").click(function () {
        clickedSearch = true;
    });

    $("#shares_button").click(function () {
        clickedShares = true;
    });

    $("#buy_button").click(function () {
        clickedBuy = true;
    });

    // Trigger click() of corresponding button if enter key is pressed in input field
    $("#symbolInput").keydown(function (event) {
        if (event.keyCode == 13) {
            event.preventDefault();
            $("#search_button").click();
        }
    });

    $("#amountInput").keydown(function (event) {
        if (event.keyCode == 13) {
            event.preventDefault();
            $("#shares_button").click();
        }
    });


    function validateBuy(form) {

        // Make sure user is searching for anything
        if (clickedSearch == true) {

            clickedSearch = false;
            if ($("#symbolInput").val() === "") {
                $("#searchfeedback").html("Search field empty");
                return false;
            }
        }

        // Make sure user isn't trying to buy too much or too little
        if (clickedShares === true || clickedBuy === true) {

            clickedShares = false;
            clickedBuy = false;

            if ($("#amountInput").val() < 1) {
                $("#sharesfeedback").html("You can't buy less than one");
                $("#amountInput").val(serverAmount);
                return false;
            }
            else if (($("#amountInput").val() * +price > +'{{ session.cash }}')) {
                $("#sharesfeedback").html("You're too poor!");
                $("#amountInput").val(serverAmount);
                return false;
            }
        }
        return true;
    }

</script>


{% endblock %}

application/templates/by.html
{% extends "layout.html" %} {% block title %} Buy {% endblock %} {% block main
%}

<div>
    <span>Buy a stock from the <a href="https://www.advfn.com/nasdaq/nasdaq.asp" target="_blank">NASDAQ index</a>. Like
        TSLA, NFLX, GOOG, DDD, STX, CCC, SBUX, FOSL... To mention a few. </span><br><br>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <! –– search bar ––>
            <div class="input-group">
                {% if form.search.errors %}
                {{ form.search(class="form-control is-invalid", autocomplete="off", autofocus=true) }}
                <div class="input-group-append">
                    <! -- search button -->
                        {{ form.search_button(class="mybtn btn btn-outline-secondary fa-text", style="border-radius: 0.25rem;", type="submit", value="&#xf002;"|safe) }}
                </div>
                <div class="invalid-feedback" style="text-align: left;">
                    {% for error in form.search.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.search(class="form-control", autocomplete="off", autofocus=true) }}
                <div class="input-group-append">
                    <! -- search button -->
                        {{ form.search_button(class="mybtn btn btn-outline-secondary fa-text", autocomplete="off", type="submit", value="&#xf002;"|safe, style="border-radius: 0.25rem;") }}
                </div>
                {% endif %}
            </div>
            <! -- end of searchbar -->

                <! -- product containter, only shows if there's a valid stock in flask session -->
                    {% if ("buystock" not in session) %}
                    <!-- User still hasn't posted anything. -->
                    {% elif "symbol" in session["buystock"] %}
                    <!-- User has searched for a valid stock. -->
                    {% set buyDict = session["buystock"] %}
                    <!-- buyDict is the dictionary with stock information. -->
                    <div class="container-fluid product-container">
                        <!-- PRODUCT -->
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-12 col-sm-6" style="padding-right: 0; padding-left: 0;">
                                    <h4 class="product-name">
                                        <strong>{{ buyDict["name"] }}</strong>
                                    </h4>
                                    <h4>
                                        <small>{{ buyDict["symbol"] }}</small>
                                    </h4>
                                </div>
                                <div class="col-12 col-sm-6 text-right" style="
              margin-top: auto;
              padding-right: 0;
              padding-left: 0;
              padding-top: 10px;
            ">
                                    <div style="
                display: flex;
                justify-content: flex-end;
                align-items: center;
              ">
                                        <!--Price to the left of input field-->
                                        <span>
                                            <strong>{{"$%.2f"|format(buyDict["price"]) }}
                                                <span class="text-muted" style="padding-right: 4px;">x</span></strong>
                                        </span>
                                        {% if form.shares.errors %}
                                        <div class="input-group float-right" style="max-width: 100px;">
                                            {{ form.shares(class="form-control is-invalid", autocomplete="off", autofocus=true, value=session['buystock']['amount'], size="4") }}
                                            <div class="input-group-append">
                                                <!-- refresh button -->
                                                {{ form.shares_button(class="mybtn btn btn-outline-secondary fa-text", value="&#xf2f1;"|safe, style="border-radius: 0.25rem;") }}
                                            </div>
                                        </div>
                                        {% else %}
                                        <!--Number input field for refresh button-->
                                        <div class="input-group float-right" style="max-width: 100px;">
                                            {{ form.shares(class="form-control", autocomplete="off", autofocus=true, value=session['buystock']['amount'], size="4") }}
                                            <div class="input-group-append">
                                                <!-- refresh button -->
                                                {{ form.shares_button(class="mybtn btn btn-outline-secondary fa-text", value="&#xf2f1;"|safe, style="border-radius: 0.25rem;") }}
                                            </div>
                                        </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            {% if form.shares.errors %}
                            <div class="feedback"
                                style="text-align: right; margin-right: -12px; color: #dc3545; font-size: 80%;">

                                <span>{{ form.shares.errors[0] }}</span>

                            </div>
                            {% endif %}
                        </div>
                        <hr />
                        <!-- END PRODUCT -->
                    </div>
                    <div class="card-footer">
                        <div class="pull-right" style="margin: 10px;">
                            <! -- buy button -->
                                <button class="mybtn btn btn-primary" type="submit" name="submit-button" value="buy">
                                    Buy
                                </button>
                                <div class="pull-right" style="margin: 5px;">
                                    Total price:
                                    <b>
                                        {% if "buytotal" in buyDict %} {{
            "$%.2f"|format(buyDict["buytotal"]) }} {% endif %}
                                    </b>
                                </div>
                        </div>
                    </div>

                    {% endif %}
    </form>
</div>


{% endblock %}

application/templates/history.html
{% extends "layout.html" %}

{% block title %}
History
{% endblock %}

{% block main %}
<div class="container mb-3 mt-3" style="text-align: left !important;">

    <table id="historytable" class="table table-striped table-bordered" style="width:100%;">
        <thead>
            <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Total</th>
                <th>Time</th>
            </tr>
        </thead>
        <tbody>
            {% for row in tran %}

            <tr>
                <td>{{row["name"]}} ({{ row["symbol"] }})</td>
                <td>{{ row["amount"] }}</td>
                <td style='{{"color: green;" if row["type"] == "sale" else "color: red;"}}'>{{ row["total_price"] }}
                </td>
                <td id="time{{loop.index}}">{{ row["time"] }}</td>
            </tr>
            <script>
                // moment library needs to be imported (in base template):
                // "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"
                var currentTime = moment.parseZone('{{ row["time"]|safe }}').local().format("ddd DD/MM/YYYY");
                document.getElementById("time{{loop.index}}").innerHTML = currentTime;
            </script>

            {% endfor %}

        </tbody>
        <tfoot>
            <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Total</th>
                <th>Time</th>
            </tr>
        </tfoot>
    </table>
</div>

<script>
    // Necessary imports: jquery, DataTables, Moment.js, DataTables plugin:
    // "Ultimate Date / Time Sorting" with moment.js - see Layout.hmtl
    $(document).ready(function () {
        $.fn.dataTable.moment("ddd DD/MM/YYYY")
        $('#historytable').DataTable({
            "order": [[3, "desc"]]
        });
    });
</script>
{% endblock %}

application/templates/layout.html
<!DOCTYPE html>

<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>C$50 Finance: {% block title %}{% endblock %}</title>

    <!-- documentation at http://getbootstrap.com/docs/4.1/, alternative themes at https://bootswatch.com/ -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" />

    <!-- https://favicon.io/emoji-favicons/money-mouth-face/ -->
    <link href="/static/favicon.ico" rel="icon" />

    <!-- base imports-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/603271f4a3.js" crossorigin="anonymous"></script>

    <!-- moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>

    <!-- for DataTables-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.bootstrap4.min.css" rel="stylesheet" />

    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>

    <!-- plugin for DataTables and moment.js ( written at the time of moment v. 2.8.4 -->
    <script src="https://cdn.datatables.net/plug-ins/1.10.21/sorting/datetime-moment.js"></script>

    <!-- my own custom styling -->
    <link href="/static/styles.css" rel="stylesheet" />


</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light border">
        <a class="navbar-brand" href="/"><span class="blue">C</span><span class="red">$</span><span
                class="yellow">5</span><span class="green">0</span>
            <span class="red">Finance</span></a>
        <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
            data-target="#navbar" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            {% if session.user_id %}
            <ul class="navbar-nav mr-auto mt-2">
                <li class="nav-item"><a class="nav-link" href="/quote">Quote</a></li>
                <li class="nav-item"><a class="nav-link" href="/buy">Buy</a></li>
                <li class="nav-item"><a class="nav-link" href="/sell">Sell</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="/history">History</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto mt-2">


                <li class="nav-item">
                    <a class="nav-link" href="/logout">Log Out</a>
                </li>
            </ul>

            {% else %}
            <ul class="navbar-nav ml-auto mt-2">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="/login">Log In</a></li>
            </ul>
            {% endif %}
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %}
    <header>
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} border text-center" role="alert">
            <span>{{ message }}</span>
        </div>
        {% endfor %}
    </header>
    {% endif %} {% endwith %}

    <main class="container main-container">
        {% if session.user_id %}
        <div class="row"
            style="margin: 0; padding-right: 12px; padding-bottom: 0; justify-content: flex-end; font-size: 130%; height: 2em;">
            <p><span style="color: #ea433b; font-size: x-large;">{{ session.username }}</span>
                <strong>{{ "$%.2f"|format(session.cash) }}</strong></p>
        </div>
        {% endif %}
        {% block main %}{% endblock %}
    </main>

    <footer class="small text-center text-muted">
        Data provided for free by
        <a href="https://iextrading.com/developer">IEX</a>. View
        <a href="https://iextrading.com/api-exhibit-a/">IEX’s Terms of Use</a>.
    </footer>


    <script type="text/javascript" src="{{ url_for('static', filename='scripts.js') }}"></script>
    <script>
        window.setTimeout(function () {
            $(".alert").fadeTo(1000, 0).slideUp(1000, function () {
                $(this).remove();
            });
        }, 2000);
    </script>
</body>

</html>

application/templates/login.html
{% extends "layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block main %}
<div class="content-section">
    <! --insert novalidate as attribute if you only want to user server side validation-->
        <form id="loginForm" onsubmit="return validateLogin(this);" method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <fieldset class="form-group" style="text-align: left;">
                <legend id="legend" class="border-bottom mb-4"></legend>
                <div class="form-group">
                    {% if form.username.errors %}
                    {{ form.username(class="form-control is-invalid", autocomplete="off", placeholder="Username") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.username(class="form-control", autocomplete="off", autofocus=true, placeholder="Username") }}
                    <div id="username-feedback" class="invalid-feedback"></div>
                    <div id="username-exists" style="color: green; display: none;"><i class="fas fa-check"></i></div>
                    {% endif %}
                </div>
                <div class="form-group">

                    {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid", autocomplete="off", placeholder="Password") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-control", autocomplete="off", placeholder="Password") }}
                    <div id="password-feedback" class="invalid-feedback"></div>
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary btn-outline-info") }}
            </div>
        </form>
</div>

{% endblock %}

application/templates/quote.html
{% extends "layout.html" %}

{% block title %}
Quote
{% endblock %}

{% block main %}
<form action="/quote" method="post" onsubmit="return validateSearch(this);">
    <div class="form-group">
        <input id="symbolInput" autocomplete="off" autofocus class="form-control" name="symbol"
            placeholder="stock symbol" type="text">
        <div id="searchfeedback" class="feedback" style="text-align: left; color: #dc3545; font-size: 80%;"></div>
    </div>
    <button id="search_button" class="btn btn-primary" type="submit">Get quote</button>
</form>

{% if quoteDict == "" %}
<!-- Nothing to see here. -->
{% else %}
<div class="container pt-5">
    <div class="table-responsive">
        <table id="jstable" class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Symbol</th>
                    <th scope="col">Time</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ quoteDict["name"] }}</td>
                    <td>{{ quoteDict["price"] }}</td>
                    <td>{{ quoteDict["symbol"] }}</td>
                    <td id="timeStamp"></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<script>
    // moment library needs to be imported (in base template):
    // "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"
    var currentTime = moment.parseZone('{{ quoteDict["isotime"]|safe }}').local().format("lll");
    document.getElementById("timeStamp").innerHTML = currentTime;
</script>
{% endif %}

<script>
    $(document).ready(function () {
        $(window).keydown(function (event) {
            if (event.keyCode == 13) {
                event.preventDefault();
            }
        });
    });

    var searchInput = document.getElementById("symbolInput");
    var clickedSearch = false;


    document.getElementById('search_button').onclick = function () {
        clickedSearch = true;
    };


    // Execute a functions when the user releases a key on the keyboard
    searchInput.addEventListener("keyup", function (event) {
        if (event.keyCode === 13) {
            document.getElementById("search_button").click();
        }
    });


    function validateSearch(form) {

        if (clickedSearch == true) {

            clickedSearch = false;
            if (searchInput.value === "") {
                document.getElementById('searchfeedback').innerHTML = "Search field empty";
                return false;
            }
        }

        return true;
    }

</script>

{% endblock %}